In [1]:
import numpy as np

In [4]:
range_array = np.arange(10) # like range in python
range_array

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

# Reshaping array

<b>Properly initialise the shape with proper division </b>

In [9]:
range_array.shape = (5,2) # change the array
range_array

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [23]:
range_array = range_array.reshape((2,5)) # returns an array
range_array

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

# Argsort - retrun indices which will sort the array 

argmin and argmax not return indices

# Argmin - first element corresponding to argsort . Min value of the array

# Argmax - last element  corresponding to argsort. Max value


in all of the cases we can explicitly provide axis. By default it is 1

In [24]:
np.argsort(range_array) # indices will be returned which will sort the array

array([[0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4]], dtype=int64)

In [21]:
np.argmin(range_array)

0

In [22]:
np.argmax(range_array)

9