In [26]:
import numpy as np

# Basics
                

In [27]:
a=np.array([1,2,3],dtype="int16")#by default dtype is int32
print(a)

[1 2 3]


In [28]:
b=np.array([[1,2,3],[2,2,3]])#2d array
print(b)

[[1 2 3]
 [2 2 3]]


In [29]:
### getting dimensions
print(a.ndim)
print(b.ndim)


1
2


In [30]:
## getting shape
print(a.shape)
print(b.shape)

(3,)
(2, 3)


In [31]:
#get dtype
a.dtype


dtype('int16')

In [32]:
#get itemsize
print(a.itemsize)
print(b.itemsize)

2
4


In a dtype is int16 so 16/8 is 2
In b dtype is int32 so 32/8 is 4



In [33]:
#get total size
print(a.size*a.itemsize)
print(a.nbytes)

6
6


#  Accessing/Changing Specific Elements, Rows, Columns, etc (slicing)

In [34]:
# a=np.array([[1,2,3,4,5,6,7],[8,9,10,11,12,13,1111111]],dtype="int18")
## above will give eerors.

In [35]:
## array must have same order elements
#(here,7.& must be present in both the list)

In [36]:
a=np.array([[1,2,3,4,5,6,7],[8,9,10,11,12,13,14]])
print(a)
print(a.shape)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]
(2, 7)


In [37]:
#Getting a specific element= [row,column]
a[1,2]

10

In [38]:
#getting a specific row
a[0,:] ### 0 means 1st row and : means all columns

array([1, 2, 3, 4, 5, 6, 7])

In [39]:
#getting a specific  columns
a[:,2] ## all rows and 3rd column

array([ 3, 10])

In [40]:
# Getting a little more fancy [startindex:endindex:stepsize]

a[0,1:7:2]#elements of index 1 to 6(7-1=6; since 7 is excluded) of first row

array([2, 4, 6])

In [41]:
## changing the elements
# a[1,5]=33
# print(a)

a[:,2]=17 #replacing elements of 2nd index from all rows
print(a)


[[ 1  2 17  4  5  6  7]
 [ 8  9 17 11 12 13 14]]


In [42]:
a[:,2]=[22,20] #replacing elements of 2nd index by 2 elements from all rows
print(a)

[[ 1  2 22  4  5  6  7]
 [ 8  9 20 11 12 13 14]]


# 3d array


In [43]:
# b=np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])

b=np.array([
    [[1,2,3], # 1st array 1st row
     [4,5,6]],
    
    [[7,8,9],  # 2nd array 1st row
     [10,11,12]]
])
print(b)


[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


In [44]:
##get specific element(work outside in)
print(b[0,1,2])

# 1st array----2nd row-----3rd element


6


In [45]:
b[:,1,:]#All arrays---2nd row---all elements

array([[ 4,  5,  6],
       [10, 11, 12]])

In [46]:
b[1,0,:2]#2nd array---1st row--1st to2nd element

array([7, 8])

In [47]:
b[1,:,:2]#2nd array---All rows--1st to 2nd element



array([[ 7,  8],
       [10, 11]])

In [48]:
#replacing elements
# the order must be same while replacing.Here we cant insert 3 values 
# b[1,:,:2]=[[10,21],[22,33]] or 
b[1,:,:2]=[10,21],[22,33]
b

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[10, 21,  9],
        [22, 33, 12]]])

# Initialising differeent types of arrays

In [49]:
#zeroes 
print(np.zeros((2,3)))#insert shape and dtype

[[0. 0. 0.]
 [0. 0. 0.]]


##if u want to insert no.of colums then specify the shape in tuple.
#Example::
np.zeros(2,3)#here error will come

TypeError                                 Traceback (most recent call last)
<ipython-input-25-bf82489adb72> in <module>
      1 ##if u want to insert no.of colums then specify the shape in tuple.
      2 #Example::
----> 3 np.zeros(2,3)#here error will come

TypeError: Cannot interpret '3' as a data type


In [50]:
#ones 
##same parameter as zeros
np.ones((3,2,4))## 3 means no.of arrays,2 means no.of rows,4means no. of elements or columns

array([[[1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.]]])

In [51]:
#Any other no.
# here parameter is shape, element and dytpe
np.full((2,2),5)

array([[5, 5],
       [5, 5]])

In [52]:
x=np.zeros((2,4))
print(x)
#Any other no.(full_like)
np.full_like(x,3)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]]


array([[3., 3., 3., 3.],
       [3., 3., 3., 3.]])

In [53]:
## another way to work with full
np.full(x.shape,5)


array([[5, 5, 5, 5],
       [5, 5, 5, 5]])

In [54]:
## Random decimal numbers
np.random.rand(2,2)##directly inserting the shape

array([[0.63216843, 0.31571938],
       [0.77475474, 0.71159744]])

In [55]:
## using the shape of an array
np.random.random_sample(x.shape)

array([[0.83276759, 0.00672718, 0.86783113, 0.66325864],
       [0.34949592, 0.84238922, 0.05731951, 0.06167957]])

In [56]:
#Random integer values
np.random.randint(7,size=(3,2))## size is the shape.
##We can also pass the x.shape in the size

array([[5, 1],
       [5, 2],
       [5, 5]])

In [57]:
np.random.randint(5,7,size=(3,2))## 7 is excluded

array([[5, 5],
       [6, 6],
       [6, 5]])

In [58]:
np.identity(3)##identity matrix and oviously its an square matrix
##parameter is no.of rows.Since  square matrix so row=column

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [59]:
#repeating the array
#one dimension
arr=np.array([1,2,3] )
r1=np.repeat(arr,3)##by default axis is 0
print(r1)


[1 1 1 2 2 2 3 3 3]


In [60]:
#t2o dimension
arr=np.array([[1,2,3]])
r1=np.repeat(arr,3,axis=0)
r2=np.repeat(arr,3,axis=1)
print("Axis(0):",r1)
print("Axis(1):",r2)

Axis(0): [[1 2 3]
 [1 2 3]
 [1 2 3]]
Axis(1): [[1 1 1 2 2 2 3 3 3]]


 Q) print this array(initialising array)

    1 1 1 1 1
    1 0 0 0 1
    1 0 9 0 1
    1 0 0 0 1
    1 1 1 1 1

In [61]:
output=np.ones((5,5))
# print(output)

zero=np.zeros((3,3))

zero[1,1]=9 # 2nd row 2nd column value will be 9
# print(zero)

output[1:4,1:4]=zero #2nd row to 4th row, replacing elements 2nd column to 4th column with zero array
print(output)

[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 9. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


# Be careful when copying arrays

In [62]:
a=np.array([1,2,3])
b=a
b[0]=100
### Here changes will be made both in b as wll as a
print("b:",b)
print("a:",a) 

b: [100   2   3]
a: [100   2   3]


##### so use b=a.copy()

In [63]:
a=np.array([1,2,3])
b=a.copy()
b[0]=100
print("b:",b)
print("a:",a) 

b: [100   2   3]
a: [1 2 3]


# Mathamatics


In [64]:
a=np.array([1,2,3])
print(a+2)
print(a-2)
print(a*2)
print(a/2)

a+=2
print(a)

a-=1
print(a)

a*=3
print(a)


a**=2
print(a)

a=a/2
print(a)



[3 4 5]
[-1  0  1]
[2 4 6]
[0.5 1.  1.5]
[3 4 5]
[2 3 4]
[ 6  9 12]
[ 36  81 144]
[18.  40.5 72. ]


In [65]:
#sin
np.sin(a)

array([-0.75098725,  0.33415118,  0.25382336])

## Linear Algebra


In [66]:
## multiplication of matrices(row of 1st matrix must be equal to column of second one)
a=np.ones((2,3))
# print(a)

b=np.full((3,2),2)
# print(b)

###Here a*b will not work as a and b are of different order.

np.matmul(a,b)


array([[6., 6.],
       [6., 6.]])

In [67]:
#Finding determinant

c=np.identity(3)
np.linalg.det(c)

1.0

Reference docs(scipy.org)

#determinants
#Trace
#Singular vector decomposition
#Eigenvalues
#Matrix Norm
#Inverse
#Etc

# Statistics

In [81]:
stats=np.array([[1,12,10],[4,5,6]])
stats

array([[ 1, 12, 10],
       [ 4,  5,  6]])

In [78]:
print(np.min(stats))
print(np.max(stats))

1
12


Axis 0 means rows wise means downward.
Axis 1 means column wise means Sidewiise 

In [80]:
print(np.min(stats,axis=0))
print(np.max(stats,axis=0))

[1 5 6]
[ 4 12 10]


array([[ 1, 12, 10]
      [ 4,  5,  6]])
Here if we see along axis 0,then,
comparision will be b/w 1st row and 2nd element and the 
return value is also an array composed of all the minimum 
values

1 and 4 is 1
12 and  5 is 5 
10 and 6 is 6

so the resultant array is [1,5,6]

In [82]:
print(np.min(stats,axis=1))
print(np.max(stats,axis=1))

[1 4]
[12  6]


Here in axis=1, the 1st row elements are compared among themselves and 2nd row among themselves.The resultant  array is composed of the elements of the min elements of both the rows

1st row: 1 12 and 10=1 
2nd row: 4 5 and 6= 4.

Resultant array=[1 4]

# Reorganising arrays


In [95]:
before=np.array([[1,2,3],[4,5,6]])

print(before)
print()
print(before.shape)
print()

## Reshaping 
after=before.reshape((6,1))
print(after)
print()
print(after.shape)

[[1 2 3]
 [4 5 6]]

(2, 3)

[[1]
 [2]
 [3]
 [4]
 [5]
 [6]]

(6, 1)


In [99]:
## Vertically stacking vactors or matrices

v1=np.array([1,2,3,4])
v2=np.array([5,6,7,8])

np.vstack([v1,v2])##vertically stacked

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [101]:
np.vstack([v1*3])## here scalar multiplication takes place

array([[ 3,  6,  9, 12]])

In [102]:
np.vstack([v1]*3)##here repeation of arrays takes  place

array([[1, 2, 3, 4],
       [1, 2, 3, 4],
       [1, 2, 3, 4]])

In [110]:
## Horizontal stacking vactors or matrices
h1=np.ones((2,2))
h2=np.zeros((2,4))

np.hstack((h1,h2)) #Horizontally stacked

array([[1., 1., 0., 0., 0., 0.],
       [1., 1., 0., 0., 0., 0.]])

# Miscellaneous


Load data  from file

NameError: name 'vxcvcx' is not defined