In [1]:
import numpy as np

### Getting all functions from numpy

In [2]:
dir(np);
len(dir(np))

600

In [3]:
ar1 = np.array ([[1,2,3],[4,5,6]])

# Axis
### For 2d columnwise(vertically down) = axis 0
### rowwise (horizontally) = axis 1

In [4]:
ar1.sum(axis=1) # printing sum row wise(horizontally)

array([ 6, 15])

In [5]:
ar1.sum(axis=0) # printing sum column wise (vertically)

array([5, 7, 9])

# Transpose of any matrix

In [6]:
ar1.transpose()

array([[1, 4],
       [2, 5],
       [3, 6]])

# Dot product


In [7]:
ar1.dot(ar1.transpose())

# or

np.dot(ar1 , ar1.transpose()) # better practice

array([[14, 32],
       [32, 77]])

## Cross product

In [8]:
np.cross(ar1,ar1) # all are 0 since cross product between same vector is always 0

array([[0, 0, 0],
       [0, 0, 0]])

# Sorting
<hr>

In [9]:
array = np.array([[11,1,22,0],[1,21,1,2]])

#### ABout
sort by default in the axis 1 

np.sort(array) -> it returns an array instead of changing the actual one

array.sort() # modifies the actual array and dont return anything

In [10]:
np.sort(array) # default is axis 1 

array([[ 0,  1, 11, 22],
       [ 1,  1,  2, 21]])

In [11]:
np.sort(array , axis=0) # axis 0 sorting only

array([[ 1,  1,  1,  0],
       [11, 21, 22,  2]])

In [12]:
# array.sort() # axis 1
array.sort(axis=0)
array

array([[ 1,  1,  1,  0],
       [11, 21, 22,  2]])

# SORTING WITH A SPECIFIC ALGORITHM
time will differ.

In [13]:
np.sort(array , axis = 1 , kind="mergesort")

array([[ 0,  1,  1,  1],
       [ 2, 11, 21, 22]])