In [1]:
import numpy as np

In [2]:
# making a numpy array

np.array([1,2,3,4,5,6]) # using list

np.array((1,2,3,5,6)) # using tuple


array([1, 2, 3, 5, 6])


# Numpy functions
<hr>

In [3]:
# creating arrays

array1 = np.array([[1,2,3,4],[22,33,44,55]])
print(array1)
print(type(array1))


[[ 1  2  3  4]
 [22 33 44 55]]
<class 'numpy.ndarray'>


In [4]:
# array shapes - rows and column

array1.shape

(2, 4)

In [5]:
# array dtype
array1.dtype

dtype('int32')

In [6]:
# creating array with dtype
np.array([[1,2,3,4],[22,33,44,55]] , dtype="float32" )

array([[ 1.,  2.,  3.,  4.],
       [22., 33., 44., 55.]], dtype=float32)

# Making blank arrays
<hr>

In [7]:
# making blank arrays with zeros

print(np.zeros(4)) # row 1 and column 4

print(np.zeros((4,5))) # providing the rows and columns in a tuple


[0. 0. 0. 0.]
[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [8]:
# making blank arrays with ones
np.ones((1,5))

array([[1., 1., 1., 1., 1.]])

In [9]:
# making array with np.empty() but it is different from the above tow
# values can be fairly any value.
np.empty((1,6))

array([[0., 0., 0., 0., 0., 0.]])

# Arithmetic operation
<hr>

In [10]:
arr = np.array([[1,2,3],[12,14,15]])

### Element wise operation
each element will be operated with their corresponding position(row and column number).

<b>So array shapes must be same</b>

<b>Also element size must be according to the dtype</b>

In [11]:
arr*arr

array([[  1,   4,   9],
       [144, 196, 225]])

In [12]:
arr+arr

array([[ 2,  4,  6],
       [24, 28, 30]])

In [13]:
arr/arr

array([[1., 1., 1.],
       [1., 1., 1.]])

### Operation with scalars

In [14]:
1/arr

array([[1.        , 0.5       , 0.33333333],
       [0.08333333, 0.07142857, 0.06666667]])

In [15]:
2*arr

array([[ 2,  4,  6],
       [24, 28, 30]])

# Slicing(nd arrays)
<hr>

##### Arrays are called rows and elements inside are called columns.
In 2d array , we one or multiple arrays inside an array [ [] ].
In 3d , arrays inside arrays inside a array. [ [ [] ] ] , [ [ [] ] ]

If it is 2d or more then by using commas we can go deep inside an array.

For nd arrays we can go n times deep

In [16]:
array_1d = np.array([1,2,3,4,5,3,6,5,64,2134,12])

array_2d = np.array( [ [1,2,3,4,5],[6,7,8,9,0] ] )

array_3d = np.array([ [ [1,2,3,4],[5,6,7,8] ] ])

In [17]:
array_1d [2:4]

array([3, 4])

In [18]:
array_2d[0,2] # 3rd element or 2nd index element or column in 1st row 0 array or 1st row array

3

In [19]:
array_2d[0 , 1:] # from 1st index to last in 0th index array

array([2, 3, 4, 5])

In [20]:
array_2d[: , 0] # printing 1st columns of all the rows. or 
                # printing 1st element of all the arrays

array([1, 6])

In [21]:
array_3d[: , : , :3] # print 3 elements of all the arrays present inside all of the arrays

array([[[1, 2, 3],
        [5, 6, 7]]])